from . import product_template_inherit
from . import meli_connector
from . import sale_order
from . import meli_sales
#from . import res_settings_inherit
from . import meli_stock
from . import meli_orders
from . import meli_orders_items
from . import meli_orders_payments
from . import meli_shipments
from . import meli_items